### ISSUE TITLE
Confusion about termquery

### ISSUE THREAD

**Issue by carmel** [quickwit-oss/tantivy#1121]
**Describe the bug**
- What did you do?

Searching with TermQuery

- What happened?

When I tested using the Wikipedia test data provided in the Readme file, I was unable to search for the title using the keyword "Japan", but I was able to search for it using the keyword "japan".
```json
{"title":"Cheerleading in Japan", "url":"https://en.wikipedia.org/wiki?curid=48692499", "body":"\nCheerleading in Japan\n\nCheerleading is a recognized sport in..."}
```
- What was expected?

When I use the keyword "Japan" or "Japan", I should be able to search for the content.

**Which version of tantivy are you using?**

tantivy = "0.15.3"

**To Reproduce**

```rust
...
let reader = index.reader().map_err(|e| e.to_string()).unwrap();

let searcher = reader.searcher();
let schema = index.schema();
let query = tantivy::query::TermQuery::new(
    tantivy::Term::from_field_text(schema.get_field("title").unwrap(), "Japan"),
    tantivy::schema::IndexRecordOption::Basic,
);

assert_eq!(query.count(&*reader.searcher()).unwrap(), 1);
```

Also, I'd like to know how to specify that a field is definitively equal to a certain value, rather than a fuzzy match.

**Comment by fulmicoton** [comment]
Your text goes through a tokenizer. The job of the tokenizer is to split your text into tokens, and possibly do extra steps that are akin to a normalization. This is configurable. 

By default the tokenizer normalization is just lowercasing your text.
When you search this means you need to use the same normalization on your query terms as what you used during tokenization.

The query parser does that automatically for you.

> Also, I'd like to know how to specify that a field is definitively equal to a certain value, rather than a fuzzy match.

Your question can be interpreted in 2 ways.
If you want a field to be searched like an ID, then you want the entire text to emit a single token.
This can be done by using `raw` as the tokenizer for your field.

If you want a field to be tokenized, but without any normalization steps, then no default tokenizer does this, but you can set up one using the building blocks in tantivy.

Following this example:
https://github.com/tantivy-search/tantivy/blob/main/examples/custom_tokenizer.rs
and/or this documentation
https://docs.rs/tantivy/0.15.3/tantivy/tokenizer/index.html

Instead of ngram3 (in the example), you could then define a "nolowercase" tokenize as follows:
```
    use tantivy::tokenizer::SimpleTokenizer;
    //...
    index
        .tokenizers()
        .register("nolowercase", SimpleTokenizer);
```

You would then need to configure your field in the schema to use this tokenizer.

```
    let mut schema_builder = Schema::builder();

    // Our first field is title.
    let text_field_indexing = TextFieldIndexing::default()
        .set_tokenizer("nolowercase") //< that's how we specify that we want to use our tokenizer.
        .set_index_option(IndexRecordOption::WithFreqsAndPositions);
    let text_options = TextOptions::default()
        .set_indexing_options(text_field_indexing)
        .set_stored();
    let title = schema_builder.add_text_field("title", text_options);
```

**Comment by carmel** [comment]
Thank you for your patience in answering, this is so helpful. By the way, one more question, does FuzzyTermQuery support multiple fields? I don't seem to find any examples of this.  @fulmicoton

**Comment by fulmicoton** [comment]
@carmel not directly. The fuzzy term query only targets one field. Of course you can run a booleanquery to make a disjunction over too FuzzyTermQuery.
