### ISSUE TITLE
Questions regarding custom weights and stopwords

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#375]
I’m planning to use tantivy for search of crates on crates.rs. I have more data to include in the search. I’m not sure if tantivy handles it, or do I have to use pre/post-processing to include it.

* overall ranking of a crate. When multiple crates match a query, I'd like my rank/popularity score included in the ranking. Can I index documents as more or less important?

* I have categories. One crate can be in multiple categories, but has a different ranking/relevance in each. Can I tune the ranking (as above) per category (to be used when searching with a category)?

* Example for faceted search would be useful.

* crates have keywords, which should get much more weight/relevance than words from their description or readme. Can there be a separate weighting for the keywords field only? Can they have their own TF-IDF? (e.g. almost every crate mentions "cargo" in its description, so its a noisy word for the readme, but crates tagged "cargo" really mean it).

* Can I set custom stopwords? For crate search "rust" and "rs" are noise. Ideally I'd like stopwords per category (when search is narrowed to a category), since e.g. "ffi" keyword is meaningless in FFI bindings category. I guess I could have a wholly separate index per category.

**Comment by fulmicoton** [comment]
- You can index some kind of importance score in a so called fast field. Right now floating point is not supported. Ideally you'd have to make it a `u64`... Then you'd need a custom scorer. 
It's not difficult and we can help with the implementation. In fact, this should probably be an example in tantivy crate.

- Yes. It requires a bit of coding (outside of tantivy) but anything can be done.

- Roger that. I'll try to add examples.

- Tantivy uses a popular flavor of Tf-Idf called BM25. The presence of a keyword increases the score, but this increase varies depending on 
   - is this considered keyword rare? 
   - is this keyword in a field that is short, (so that you get naturally tags  > title > text) ?
It will do the right thing for `cargo`. 

- You can set custom stop words. That would deserve an example too.

**Comment by fulmicoton** [comment]
Closing
