### ISSUE TITLE
load_searchers documentation is unclear

### ISSUE THREAD

**Issue by kornelski** [quickwit-oss/tantivy#414]
`load_searchers` is used in the example, and documented as:

> Creates a new generation of searchers after a change of the set of searchable indexes.
> This needs to be called when a new segment has been published or after a merge.

The documentation is unclear to me, since I don't know what "generation of searchers" is. I'm also not using segments or merging directly, but only higher-level `commit()`.

But what's most unclear to me is whether it *has* to be called after `commit()`, once ever, or whether it has to be called every time when starting search, or every time when starting application.

I'm implementing indexing and searching in separate executables, so I'm also wondering whether this is needed only to update in-memory state of the object, and therefore unnecessary when searching is done by another application only.

**Comment by fulmicoton** [comment]
The documentation is indeed quite unclear.

So ... regarding your question... A searcher is like a handle that gives access to a specific commit of your index. As long as you hold this handle, you are guaranteed that the data is available.
If your search request is complicated and actually requires running more than one request, as long as you hold the same `searcher` the whole time, you are guaranteed to see a consistent view of your index.
(e.g. a document will not disappear in between to queries). You are also guaranteed that you won't have bad surprises, such as an error because a file has been garbage collected.

The index holds a pool of such searcher... 
Calling `load_searcher` checks if the last commit is different, create searcher for the new commit. Add these new searchers in the pool. Also the update appears all at once : you are guaranteed that if you call searcher in a row, the commit associated to the second call to searcher is always fresher than the one for the first call.
 
We'll eventually make it an internal API and have an `IndexReader` in charge of loading searchers for you, base on a given policy.
The default policy will do what 95% of users want : the freshest available index automatically.
The implementation will consist in watching `meta.json` and calling `load_searchers()` whenever it changes. You probably want to implement somethign like that too.

One more thing : in tantivy 0.6 there is a race condition that can happen when using load_searcher() from a different process. `load_searcher()` then just returns an Error and retrying is ok.
In master, and in the upcoming tantivy 0.7 the bug is fixed.

The bug technically has never been triggered, so I assume it is low probability, but it exists.

**Comment by kornelski** [comment]
Thanks. That's much clearer.

**Comment by fulmicoton** [comment]
Leaving the ticket open to make sure the documentation is updated.
