### ISSUE TITLE
open_in_dir returns LockError(MetaLock)

### ISSUE THREAD

**Issue by madmaxio** [quickwit-oss/tantivy#445]
While rev = "ee681a4dd1eebb7902f1532861081435171f3ac4" works correctly, linux gnu

**Comment by fulmicoton** [comment]
This is expected behavior if you open a directory that was used by a tantivy that crashed with a bad timing .

Crash here includes turning off your computer or killing the process. 

Your directory is not corrupted. You can simply remove the lock file that is in the directory. `.metasomethinglock`.
This should fix the pb.

If you observe the pb again without any crash, etc, then there is probably a bug. Please report here with at much information as you can.

Especially do you use a custom directory a, what is your filesystem, what is your OS.
Ideally please share some code or describe what it is doing.

**Comment by madmaxio** [comment]
The bug has gone after recent updates, I believe something was wrong with my file system or folder locking. Thank you for your time.
