### ISSUE TITLE
Correct way to recover original Path from Facet?

### ISSUE THREAD

**Issue by teovoinea** [quickwit-oss/tantivy#580]
I am trying to recover a file path from a facet. I noticed in the docs there is [`encoded_bytes`](https://tantivy-search.github.io/tantivy/tantivy/schema/struct.Facet.html#method.encoded_bytes) which for some reason is `encoded_str` on my machine, maybe the docs aren't up to date?

In any case my solution so far has been something like this

```rust
let mut location = String::from("/");
location.push_str(my_facet.encoded_str().replace(char::from(0), "/"));
```

Is this the right way to handle it?

What happens when I insert a windows style path with no leading `/` eg: `C:\path\to\file`?

**Comment by fulmicoton** [comment]
RIght now it seem you can only use the `Display` implementation.

It will escape `/` characters that are not meant to be a separator by  a `\`.
```rust
let path = format!("{}", facet) 
```

I leave the bug open to introduce a simpler method than calling Display.

For the second question, your path is required to be  `/a/b/c`.
Just preprocess your filepath as `/c/path/to` (i would not include the filepath, and stop at the parent directory.)

**Comment by fulmicoton** [comment]
Reopening... @fdb-hiroshima Your patch is ok, but I think originally @teovoinea wanted a string representation of the path eg: `//papa_branch/kiddie_branch/leaf`

**Comment by fulmicoton** [comment]
@halvorboe your impl is incorrect, but this is probably due to confusing existing unit test.

The existing implementation in display is correct. Could you simply copy paste the logic from `fmt::Display` and call your method in `fmt::Display`. No need to care about the extra allocs.


Explanation:
There are only two representations of Facets:

The text one is `//toto/titi`.
The different step of the path may contain `/` or `\` in which case it needs to be escaped by `\`

The "binary" one is `0u8` separated. The steps are not escaped.
