### ISSUE TITLE
Generic Database?

### ISSUE THREAD

**Issue by naturallymitchell** [quickwit-oss/tantivy#83]
If you factored out tantivy's file indexing feature, would tantivy basically stand as a (speed optimized, also for large text fields) database backend with an API supporting a single expression type, [wildcard expressions](http://jmespath.org/specification.html#wildcard-expressions)?

**Comment by fulmicoton** [comment]
For the moment, depending on the DB, integrating tantivy as a free-text search engine for the records in the DB ranges from quite challenging to impossible.

Having more flexibility on implementing new `Directory` (the abstraction for the data storage) will come eventually, but in the near future, we should focus on just making `tantivy` a decent search engine.

Wildcard expression are not supported yet. It should be relatively simple since `tantivy` relies on the `fst` crate. I thought there was a ticket for that, apparently there is none, so I will create one.
