### ISSUE TITLE
Fuzzy matching in query parser

### ISSUE THREAD

**Issue by Bendabir** [quickwit-oss/tantivy#947]
Hello,
I'm playing around with Tantivy and I was wondering why fuzzy matching is not supported by the query parser. Is there any particular reason to this ? Is this feature juste missing in the query parser or is there something more specific to be aware of ?
Issue #435 states that fuzzy query only works for a single term. Is this still true ?
I did some digging into the issues, PRs, code and documentation and I couldn't find anything that would lead me on track on these questions.

Thanks !

**Comment by fulmicoton** [comment]
>  Is there any particular reason to this ?

Nobody implemented it. Having fuzziness implemented by default or enabled in a sloppy manner can  can backfire.

> Issue #435 states that fuzzy query only works for a single term. Is this still true ?

Yes... Right now FuzzyTermQuery only handle the case of a single term. 
It is reasonably simple however to split a query into several tokens, map these tokens into FuzzyTermQuery and combine those into a BooleanQuery.

That is not very efficient however. I believe the right implementation should require several search passes, and some business logic to enable a longer levenshtein distance for longer terms... I haven't seen the right implementation anywhere in the opensource world however.
Again the reason why it is not in tantivy is because I did not have the need, and nobody contributed it.

**Comment by Bendabir** [comment]
Thanks a lot for your reply, it makes things way clearer now !
