### ISSUE TITLE
Is tantivy suited for 1-5 billions web pages?

### ISSUE THREAD

**Issue by mariusa** [quickwit-oss/tantivy#956]
Hi, I'm trying to see if tantivy is suited for indexing/searching a 1-5 billion web pages. eg Typesense loads all index in memory and it must fit, so it won't work.
You mention 'distributed' is not supported by default.  Adding toshi or bayard on top would be a good solution?
What would you recommend?

Is there a doc similar to https://github.com/valeriansaliou/sonic/blob/master/INNER_WORKINGS.md ?

Thanks!

**Comment by fulmicoton** [comment]
Absolutely. I personally indexed more than a billion page and a desktop with 8GB of RAM :).

But nothing is helping you for distribution at this point. 
Bayard and Toshi won't help because, AFAIK they do not support sharding yet.

However, implementing distributed search is rather easy... Especially due to the way collector are implemented.

If you have 30mn to casually discuss your use case, feel free to book a meeting with me,
I'd love to know more about your use case.
